# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import control_plane_pb2 as control__plane__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control_plane_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FilesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFile = channel.unary_unary(
                '/cloud_drive.api.v1.FilesService/CreateFile',
                request_serializer=control__plane__pb2.CreateFileRequest.SerializeToString,
                response_deserializer=control__plane__pb2.FileResource.FromString,
                _registered_method=True)
        self.GetFile = channel.unary_unary(
                '/cloud_drive.api.v1.FilesService/GetFile',
                request_serializer=control__plane__pb2.GetFileRequest.SerializeToString,
                response_deserializer=control__plane__pb2.FileResource.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/cloud_drive.api.v1.FilesService/ListFiles',
                request_serializer=control__plane__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=control__plane__pb2.ListFilesResponse.FromString,
                _registered_method=True)


class FilesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFile,
                    request_deserializer=control__plane__pb2.CreateFileRequest.FromString,
                    response_serializer=control__plane__pb2.FileResource.SerializeToString,
            ),
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=control__plane__pb2.GetFileRequest.FromString,
                    response_serializer=control__plane__pb2.FileResource.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=control__plane__pb2.ListFilesRequest.FromString,
                    response_serializer=control__plane__pb2.ListFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud_drive.api.v1.FilesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud_drive.api.v1.FilesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FilesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud_drive.api.v1.FilesService/CreateFile',
            control__plane__pb2.CreateFileRequest.SerializeToString,
            control__plane__pb2.FileResource.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud_drive.api.v1.FilesService/GetFile',
            control__plane__pb2.GetFileRequest.SerializeToString,
            control__plane__pb2.FileResource.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud_drive.api.v1.FilesService/ListFiles',
            control__plane__pb2.ListFilesRequest.SerializeToString,
            control__plane__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UploadsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/cloud_drive.api.v1.UploadsService/CreateSession',
                request_serializer=control__plane__pb2.CreateUploadSessionRequest.SerializeToString,
                response_deserializer=control__plane__pb2.CreateUploadSessionResponse.FromString,
                _registered_method=True)
        self.AppendChunk = channel.unary_unary(
                '/cloud_drive.api.v1.UploadsService/AppendChunk',
                request_serializer=control__plane__pb2.AppendUploadChunkRequest.SerializeToString,
                response_deserializer=control__plane__pb2.AppendUploadChunkResponse.FromString,
                _registered_method=True)
        self.Finalize = channel.unary_unary(
                '/cloud_drive.api.v1.UploadsService/Finalize',
                request_serializer=control__plane__pb2.FinalizeUploadRequest.SerializeToString,
                response_deserializer=control__plane__pb2.FinalizeUploadResponse.FromString,
                _registered_method=True)
        self.Abort = channel.unary_unary(
                '/cloud_drive.api.v1.UploadsService/Abort',
                request_serializer=control__plane__pb2.AbortUploadRequest.SerializeToString,
                response_deserializer=control__plane__pb2.AbortUploadResponse.FromString,
                _registered_method=True)
        self.DownloadChunks = channel.unary_stream(
                '/cloud_drive.api.v1.UploadsService/DownloadChunks',
                request_serializer=control__plane__pb2.DownloadChunkRequest.SerializeToString,
                response_deserializer=control__plane__pb2.DownloadChunk.FromString,
                _registered_method=True)


class UploadsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Finalize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UploadsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=control__plane__pb2.CreateUploadSessionRequest.FromString,
                    response_serializer=control__plane__pb2.CreateUploadSessionResponse.SerializeToString,
            ),
            'AppendChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendChunk,
                    request_deserializer=control__plane__pb2.AppendUploadChunkRequest.FromString,
                    response_serializer=control__plane__pb2.AppendUploadChunkResponse.SerializeToString,
            ),
            'Finalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Finalize,
                    request_deserializer=control__plane__pb2.FinalizeUploadRequest.FromString,
                    response_serializer=control__plane__pb2.FinalizeUploadResponse.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=control__plane__pb2.AbortUploadRequest.FromString,
                    response_serializer=control__plane__pb2.AbortUploadResponse.SerializeToString,
            ),
            'DownloadChunks': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadChunks,
                    request_deserializer=control__plane__pb2.DownloadChunkRequest.FromString,
                    response_serializer=control__plane__pb2.DownloadChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud_drive.api.v1.UploadsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud_drive.api.v1.UploadsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UploadsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud_drive.api.v1.UploadsService/CreateSession',
            control__plane__pb2.CreateUploadSessionRequest.SerializeToString,
            control__plane__pb2.CreateUploadSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud_drive.api.v1.UploadsService/AppendChunk',
            control__plane__pb2.AppendUploadChunkRequest.SerializeToString,
            control__plane__pb2.AppendUploadChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Finalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud_drive.api.v1.UploadsService/Finalize',
            control__plane__pb2.FinalizeUploadRequest.SerializeToString,
            control__plane__pb2.FinalizeUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud_drive.api.v1.UploadsService/Abort',
            control__plane__pb2.AbortUploadRequest.SerializeToString,
            control__plane__pb2.AbortUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cloud_drive.api.v1.UploadsService/DownloadChunks',
            control__plane__pb2.DownloadChunkRequest.SerializeToString,
            control__plane__pb2.DownloadChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OperationsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/cloud_drive.api.v1.OperationsService/Get',
                request_serializer=control__plane__pb2.GetOperationRequest.SerializeToString,
                response_deserializer=control__plane__pb2.Operation.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/cloud_drive.api.v1.OperationsService/Cancel',
                request_serializer=control__plane__pb2.CancelOperationRequest.SerializeToString,
                response_deserializer=control__plane__pb2.CancelOperationResponse.FromString,
                _registered_method=True)


class OperationsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=control__plane__pb2.GetOperationRequest.FromString,
                    response_serializer=control__plane__pb2.Operation.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=control__plane__pb2.CancelOperationRequest.FromString,
                    response_serializer=control__plane__pb2.CancelOperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud_drive.api.v1.OperationsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud_drive.api.v1.OperationsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperationsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud_drive.api.v1.OperationsService/Get',
            control__plane__pb2.GetOperationRequest.SerializeToString,
            control__plane__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud_drive.api.v1.OperationsService/Cancel',
            control__plane__pb2.CancelOperationRequest.SerializeToString,
            control__plane__pb2.CancelOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SharingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShareFile = channel.unary_unary(
                '/cloud_drive.api.v1.SharingService/ShareFile',
                request_serializer=control__plane__pb2.ShareFileRequest.SerializeToString,
                response_deserializer=control__plane__pb2.ShareFileResponse.FromString,
                _registered_method=True)
        self.ListShares = channel.unary_unary(
                '/cloud_drive.api.v1.SharingService/ListShares',
                request_serializer=control__plane__pb2.ListSharesRequest.SerializeToString,
                response_deserializer=control__plane__pb2.ListSharesResponse.FromString,
                _registered_method=True)


class SharingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ShareFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListShares(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SharingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShareFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareFile,
                    request_deserializer=control__plane__pb2.ShareFileRequest.FromString,
                    response_serializer=control__plane__pb2.ShareFileResponse.SerializeToString,
            ),
            'ListShares': grpc.unary_unary_rpc_method_handler(
                    servicer.ListShares,
                    request_deserializer=control__plane__pb2.ListSharesRequest.FromString,
                    response_serializer=control__plane__pb2.ListSharesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud_drive.api.v1.SharingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud_drive.api.v1.SharingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SharingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ShareFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud_drive.api.v1.SharingService/ShareFile',
            control__plane__pb2.ShareFileRequest.SerializeToString,
            control__plane__pb2.ShareFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListShares(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud_drive.api.v1.SharingService/ListShares',
            control__plane__pb2.ListSharesRequest.SerializeToString,
            control__plane__pb2.ListSharesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
